
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
    version: blue   # This will change dynamically
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
